FROM python:3.11
COPY . /app
WORKDIR /app
RUN apt update && apt upgrade -y && \
    apt-get install -y libgl1-mesa-glx && \
    pip install --no-cache-dir -r /app/requirements.txt
ENTRYPOINT bash run_celery.sh