# Generated by Django 5.2.4 on 2025-08-18 14:01

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_order_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnails',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnails',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
