name: 'Test Coverage with Celery'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options:
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for services
        run: |
          sleep 10

      - name: Start Celery worker
        run: |
          celery -A orders worker -l info -P gevent --detach

      - name: Run tests with coverage
        env:
          POSTGRES_DB_NAME: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/1
          DJANGO_SETTINGS_MODULE: orders.settings

        run: |
          coverage run --source='.' manage.py test
          coverage xml -o coverage.xml    
          coverage report

      - name: Extract and format coverage percentage
        id: coverage
        run: |
          # Извлекаем и форматируем процент покрытия
          COVERAGE=$(grep -oPm1 '(?<=line-rate=")[^"]+' coverage.xml | head -1 | awk '{printf "%.2f", $1*100}')
          
          # Проверяем валидность значения
          if [[ ! "$COVERAGE" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
            echo "::error::Invalid coverage value extracted: $COVERAGE"
            exit 1
          fi
          
          COVERAGE_PERCENTAGE="${COVERAGE}%"
          # Экспортируем переменные
          echo "coverage=${COVERAGE}" >> $GITHUB_OUTPUT
          echo "COVERAGE=${COVERAGE}" >> $GITHUB_ENV
          echo "COVERAGE_PERCENTAGE=${COVERAGE_PERCENTAGE}" >> $GITHUB_ENV
          
          echo "Extracted coverage: ${COVERAGE_PERCENTAGE}"

      - name: Generate coverage badge
        run: |
          # Определяем цвет бейджа
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            COLOR="red"
          elif (( $(echo "$COVERAGE < 90" | bc -l) )); then
            COLOR="yellow"
          else
            COLOR="brightgreen"
          fi
          
          # Формируем URL бейджа
          BADGE_URL="https://img.shields.io/badge/Coverage-${COVERAGE_PERCENTAGE}-${COLOR}?logo=python&style=flat-square"
          BADGE_MARKDOWN="![Test Coverage](${BADGE_URL})"
          
          echo "=============================================="
          echo "ДИНАМИЧЕСКИЙ БЕЙДЖ ДЛЯ README.md"
          echo "=============================================="
          echo "Замените в вашем README.md строку с бейджем на:"
          echo ""
          echo "${BADGE_MARKDOWN}"
          echo ""
          echo "Текущее покрытие: ${COVERAGE_PERCENTAGE}"
          echo "=============================================="
          
          # Сохраняем для последующих шагов
          echo "BADGE_URL=${BADGE_URL}" >> $GITHUB_ENV
          echo "BADGE_MARKDOWN=${BADGE_MARKDOWN}" >> $GITHUB_ENV

      - name: Create workflow summary
        if: always()
        run: |
          echo "### Результаты тестового покрытия" >> $GITHUB_STEP_SUMMARY
          echo "**Текущее покрытие:** ${COVERAGE_PERCENTAGE}" >> $GITHUB_STEP_SUMMARY
          echo "**Markdown для бейджа:**" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`markdown" >> $GITHUB_STEP_SUMMARY
          echo "${BADGE_MARKDOWN}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "**Badge URL:**" >> $GITHUB_STEP_SUMMARY
          echo "${BADGE_URL}" >> $GITHUB_STEP_SUMMARY